name: jekyll-cd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@v2
      - name: 🧪 Build and deploy
        uses: EdricChan03/action-build-deploy-ghpages@v2.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # The GitHub installation token. Note: You can also use ${{ github.token }}
          # gh_pages_token: ${{ secrets.GH_PAGES_TOKEN }} # Note: You have to create this yourself - see the "Secrets used" section above for more info (This input does not have a default value - you have to supply this yourself) (As of 15 Feb 2020, this is no longer needed - see https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/46519/highlight/true#M6551)
          gh_pages_branch: deploy # The GitHub Pages branch to deploy the site to
          gh_pages_dist_folder: docs # The folder to build the site to
          gh_pages_commit_message: Deploy with jekyll-cd # The commit message to use when deploying the site
          jekyll_build_opts: JEKYLL_ENV=production # Options to pass to the Jekyll build command.
          committer_username: $GITHUB_ACTOR # The username to use for the committer of the commit
          committer_email: $GITHUB_ACTOR@users.noreply.github.com # The email to use for the committer of the commit
          git_force: true # Whether to use the --force flag when pushing the commit
